version: "3"

services:
  vote:
    build: .
    command: 
    - python 
    - app.py
    ports:
      - "5000:80"

    depends_on:
      - "redis"
      - "db"

  redis:
    image: redis:alpine

  db:
    image: postgres:9.4
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
